Presentation/Nop.Web/Models/SellYourGear/CommonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Treefort.Portal.Queries.Home;



namespace Nop.Web.Models.SellYourGear
{
    public class CommonViewModel
    {
        public bool IsFranchiseSite { get; set; }
        public RemoteControlPage RcContent { get; set; }
    }
}

Presentation/Nop.Web/Models/SellYourGear/FormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Treefort.Portal.Queries.Home;


namespace Nop.Web.Models.SellYourGear
{
    public class FormViewModel
    {
        public int LocationId { get; set; }
        [Required] public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
		public string ContactPreference { get; set; }
        
		public string City { get; set; }
        public string State { get; set; }
        [Required] public string Zip { get; set; }

        public bool IsFranchiseSite { get; set; }

        public RemoteControlPage RcContent { get; set; }

        public SellUsPicture PictureOne { get; set; }
        public SellUsPicture PictureTwo { get; set; }
        public SellUsPicture PictureThree { get; set; }
        public SellUsPicture PictureFour { get; set; }

        [Display(Name = "Make and Model")]
        [Required] public string MakeAndModel { get; set; }
        public string Color { get; set; }
        public string Year { get; set; }

        [Display(Name = "Describe Condition")]
        public string Describe { get; set; }
        public string Modifications { get; set; }

        [Display(Name="Gear Type")]
        public string GearType { get; set; }
        public string Condition { get; set; }

        public IEnumerable<SelectListItem> GearTypeOptions { get; set; }
        public IEnumerable<SelectListItem> ConditionOptions { get; set; }
		public IEnumerable<SelectListItem> ContactPreferenceOptions { get; set; }

        public class SellUsPicture
        {
            [UIHint("Picture")]
            public int PictureId { get; set; }
            public string PictureUrl { get; set; }
        }
    }
}

Presentation/Nop.Web/Controllers/OwnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using System.Xml.Linq;
using Nop.Core;
using Nop.Services.Logging;
using Nop.Web.Framework.Controllers;
using SimpleHoneypot.ActionFilters;
using SimpleHoneypot.Extensions;
using Treefort.Common.Mvc;
using Treefort.Portal;
using Treefort.Portal.Queries.Home;
using Treefort.Portal.Queries.Own;
using Treefort.Portal.Services;
using Winmark.CrmLeadIntegration;

namespace Nop.Web.Controllers
{
    public class OwnController : BaseNopController
    {
        private readonly IWorkContext _context;
        private ITerritoryInfoViewModelQuery _territoryInfoViewModelQuery { get; set; }
        private ITerritoriesViewModelQuery _territoriesViewModelQuery { get; set; }
        private IOwnPageViewModelQuery _ownPageViewModelQuery { get; set; }
        private IGetQualifyViewModelQuery _getQualifyViewModelQuery { get; set; }
        private IRemoteControlViewModelQuery _remoteControlViewModelQuery { get; set; }
		private ILogger _logger { get; set; }

        private readonly IPrequalificationService _mailService;

        public OwnController(
            IWorkContext context
            , ITerritoryInfoViewModelQuery territoryInfoViewModelQuery
            , ITerritoriesViewModelQuery territoriesViewModelQuery
            , IOwnPageViewModelQuery ownPageViewModelQuery
            , IGetQualifyViewModelQuery getQualifyViewModelQuery
            , IPrequalificationService mailService
            , IRemoteControlViewModelQuery remoteControlViewModelQuery
			, ILogger logger)
        {
            _context = context;
            _territoryInfoViewModelQuery = territoryInfoViewModelQuery;
            _territoriesViewModelQuery = territoriesViewModelQuery;
            _ownPageViewModelQuery = ownPageViewModelQuery;
            _getQualifyViewModelQuery = getQualifyViewModelQuery;
            _mailService = mailService;
            _remoteControlViewModelQuery = remoteControlViewModelQuery;
	        _logger = logger;
        }


        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (_context.SiteId != KnownIds.Website.Corporate) {
                filterContext.Result = RedirectToCorporateVersionOfUrl();
                return;
            }
            base.OnActionExecuting(filterContext);
        }


        public virtual ActionResult Index()
        {
            var model = _ownPageViewModelQuery.Execute("/own");
            ViewBag.HideOwnMgrFooter = true;
            return View(model);
        }

        public virtual ActionResult FAQ()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/about/frequently-asked-questions/");
        }

        public virtual ActionResult FranchiseeTestimonials()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/testimonials");
        }

        public virtual ActionResult Support()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/support");
        }
        public virtual ActionResult Investment()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/investment");
        }

        //public virtual ActionResult CanadianInvestment()
        //{
        //    var model = _ownPageViewModelQuery.Execute("/own-a-pias/canadian-investment");

        //    return View(model);
        //}

        public virtual ActionResult Territories(string id = "")
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/territories");
        }

        public virtual ActionResult Qualify()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/qualification-form");
        }

       

        public virtual ActionResult QualifyTerms()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/support");
        }

      
        public virtual ActionResult QualifyConfirm()
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/support");
        }

        public virtual ActionResult Commercials(string videoNumber)
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/franchise-commercials");
        }

        public virtual ActionResult FranchiseMovies(string videoNumber)
        {
            var model = new CommercialVideoPlayerViewModel();
            model.videoNumber = String.IsNullOrEmpty(videoNumber) ? "1" : videoNumber;
            return View(model);
        }

        //public virtual ActionResult StoreView(string videoNumber)
        //{
        //    var model = new CommercialVideoPlayerViewModel();

        //    model.videoNumber = String.IsNullOrEmpty(videoNumber) ? "1" : videoNumber;

        //    return View(model);
        //}

        public virtual ActionResult Testimonials(string id)
        {
            return RedirectPermanent("http://www.winmarkfranchises.com/music-go-round/testimonials");
        }

        public virtual ActionResult TestimonialLinks(string id)
        {
            var m = new TestimonialLinksViewModel();
            m.Videos = GetTestimonialsFromXml();
            return PartialView("_TestimonialLinks", m);
        }

        public virtual ActionResult TestimonialWidget()
        {
            var model = new TestimonialWidgetViewModel();

            model.Videos = GetTestimonialsFromXml();

            foreach (var v in model.Videos)
            {
                v.Size = new System.Drawing.Size(300, 221);
            }

            return PartialView("_TestimonialWidget", model);
        }

        private List<VideoPlayerSettings> GetTestimonialsFromXml()
        {
            var cacheKey = "testimonials";
            var filePath = Server.MapPath("~/App_Data/testimonials.xml");

            var results = (ControllerContext.HttpContext.Cache[cacheKey] as List<VideoPlayerSettings>);
            if (results == null)
            {
                var doc = XDocument.Load(filePath);
                if (doc.Descendants("video").Any())
                {
                    results = (from e in doc.Descendants("video") select new VideoPlayerSettings(e)).ToList();

                    foreach (var v in results)
                    {

                        v.EnableDownload = false;
                        v.ExpressInstall = "https://s3.amazonaws.com/playitagainsports.com/expressInstall.swf";
                        v.Swf = "https://s3.amazonaws.com/playitagainsports.com/flowplayer-3.2.4.swf";
                    }

                    ControllerContext.HttpContext.Cache.Insert(cacheKey, results, new System.Web.Caching.CacheDependency(filePath));
                }
                if (results == null)
                {
                    results = new List<VideoPlayerSettings>();
                }
            }
            return results;
        }

        public bool IsAjaxRequest
        {
            get { return (HttpContext.Request.Headers["X-Requested-With"] ?? string.Empty) == "XMLHttpRequest"; }
        }

        public void AddErrors(IEnumerable<ControllerError> errors)
        {
            if (errors != null)
            {
                foreach (var e in errors)
                {
                    AddError(e);
                }
            }
        }
        public bool HasErrors
        {
            get
            {
                return this.Errors.Count > 0;
            }
        }

        public void AddError(ControllerError e)
        {
            this.Errors.Add(e);
            ModelState.AddModelError(e.Key, e.Message);
        }

        private List<ControllerError> _Errors = new List<ControllerError>();
        public List<ControllerError> Errors
        {
            get { return _Errors; }
            set { _Errors = value; }
        }

    }
}

Presentation/Nop.Web/Controllers/SellYourGearController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nop.Core;
using Nop.Services.Media;
using Nop.Web.Framework.Security;
using Nop.Web.Models.SellYourGear;
using SimpleHoneypot.ActionFilters;
using SimpleHoneypot.Extensions;
using Treefort.Common.Mvc;
using Treefort.Portal;
using Treefort.Portal.Queries.Home;
using Treefort.Portal.Services;



namespace Nop.Web.Controllers
{
    public class SellYourGearController : BaseNopController
    {
        private readonly IWorkContext _context;
        private readonly ISellYourGearService _sellYourGearService;
        private readonly IPictureService _pictureService;
        private readonly IRemoteControlViewModelQuery _remoteControlViewModelQuery;
        private readonly ILocationService _locationService;

        public SellYourGearController(IWorkContext context
            , IRemoteControlViewModelQuery remoteControlViewModelQuery
			, ISellYourGearService sellYourGearService
			, IPictureService pictureService
            , ILocationService locationService)
        {
	        _context = context;
            _remoteControlViewModelQuery = remoteControlViewModelQuery;
	        _sellYourGearService = sellYourGearService;
	        _pictureService = pictureService;
            _locationService = locationService;
        }


        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.AutoPlay = false;
            var model = new CommonViewModel();
            model.RcContent = _remoteControlViewModelQuery.Execute("sellusyourgear");
            model.IsFranchiseSite = _context.SiteId != KnownIds.Website.Corporate;

            return View(model);
        }


        [HttpGet]
        public ActionResult Submitted()
        {
            var model = new CommonViewModel();
            model.RcContent = _remoteControlViewModelQuery.Execute("sellusyourgear");
            model.IsFranchiseSite = _context.SiteId != KnownIds.Website.Corporate;

            return View(model);
        }


        public ActionResult FindLocations(string zip)
        {
            ViewBag.Zip = zip;
            var locations = _locationService.GetLocationsByPostalCode(zip, int.MaxValue, 60);
            return locations.Any() ? PartialView("_SelectLocation", locations) : PartialView("_OutOfRange");
        }

        [HttpGet]
        [NopHttpsRequirement(SslRequirement.Yes)]
        public ActionResult Form(int locationId, string zip)
        {
            var model = new FormViewModel {LocationId = locationId, Zip = zip};
            FillSellYourGearDropDowns(model);
            model.PictureOne = new FormViewModel.SellUsPicture();
            model.PictureTwo = new FormViewModel.SellUsPicture();
            model.PictureThree = new FormViewModel.SellUsPicture();
            model.PictureFour = new FormViewModel.SellUsPicture();
            model.RcContent = _remoteControlViewModelQuery.Execute("sellusyourgear");
            model.IsFranchiseSite = _context.SiteId != KnownIds.Website.Corporate;

            return View(model);
        }

        [HttpPost]
        [Honeypot(true)]
        [NopHttpsRequirement(SslRequirement.Yes)]
        public ActionResult Form(FormViewModel model)
        {
            if (Request.HoneypotFaild())
            {
                return RedirectToAction("Submitted");
            }

            if (string.IsNullOrEmpty(model.Phone) && string.IsNullOrEmpty(model.Email))
            {
                ModelState.AddModelError("Phone", "Please provide either a phone number or an email address for us to reach you.");
            }

            if (!ModelState.IsValid)
            {
                FillSellYourGearDropDowns(model);
                model.RcContent = _remoteControlViewModelQuery.Execute("sellusyourgear");
                model.IsFranchiseSite = _context.SiteId != KnownIds.Website.Corporate;
                return View(model);
            }

            var request = new SellYourGearSubmissionRequest
            {
                LocationId = model.LocationId,
                CustomerName = model.Name,
                EmailAddress = model.Email,
                PhoneNumber = model.Phone,
                ContactPreference = model.ContactPreference,
                City = model.City,
                Region = model.State,
                PostalCode = model.Zip,
                GearType = model.GearType,
                MakeAndModel = model.MakeAndModel,
                Color = model.Color,
                Year = model.Year,
                Condition = model.Condition,
                Describe = model.Describe,
                Modifications = model.Modifications,
                Picture1 = GetPictureBytes(model.PictureOne),
                Picture2 = GetPictureBytes(model.PictureTwo),
                Picture3 = GetPictureBytes(model.PictureThree),
                Picture4 = GetPictureBytes(model.PictureFour)
            };

            _sellYourGearService.Submit(request);

            return RedirectToAction("Submitted");
        }

        private SellYourGearSubmissionRequest.UploadedPicture GetPictureBytes(FormViewModel.SellUsPicture uploadedPicture)
        {
            if (uploadedPicture == null || uploadedPicture.PictureId == 0) { return null; }

            var pic = _pictureService.GetPictureById(uploadedPicture.PictureId);
            if (pic == null) { return null; }

            var bytes = _pictureService.LoadPictureBinary(pic);

            return bytes == null || bytes.Length == 0
                        ? null
                        : new SellYourGearSubmissionRequest.UploadedPicture { Bytes = bytes, MimeType = pic.MimeType };
        }

        private void FillSellYourGearDropDowns(FormViewModel model)
        {
            model.GearTypeOptions = new BindingList<SelectListItem> {
                    new SelectListItem {Value = "Guitar", Text = "Guitar", Selected = true},
                    new SelectListItem {Value = "Percussion", Text = "Percussion"},
                    new SelectListItem {Value = "Band", Text = "Band"},
                    new SelectListItem {Value = "Keyboard", Text = "Keyboard"},
                    new SelectListItem {Value = "Pro Sound", Text = "Pro Sound",},
                    new SelectListItem {Value = "Accessories", Text = "Accessories"},
                    new SelectListItem {Value = "Other", Text = "Other"}
                };

            model.ConditionOptions = new BindingList<SelectListItem> {
                    new SelectListItem {Value = "Very Good", Text = "Very Good - little wear or use", Selected = true},
                    new SelectListItem {Value = "Good", Text = "Good - used but still in great shape"},
                    new SelectListItem {Value = "Average", Text = "Average - plenty of use, but still usable"}
                };

            model.ContactPreferenceOptions = new BindingList<SelectListItem> {
                    new SelectListItem {Value = "", Text = "", Selected = true},
                    new SelectListItem {Value = "Phone", Text = "Phone"},
                    new SelectListItem {Value = "Email", Text = "Email"}
                };
        }

    }
}

Presentation/Nop.Web/Views/SellYourGear/Form.cshtml
@using SimpleHoneypot.HtmlHelpers
@model Nop.Web.Models.SellYourGear.FormViewModel

@{
    Html.AppendTitleParts(Model.RcContent.Meta.Title);
    Html.AppendMetaDescriptionParts(Model.RcContent.Meta.MetaDescription);
    Layout = "~/Views/Shared/_ColumnsTwoRightColumn.cshtml";
    Html.AppendScriptParts(@Url.Content("~/Scripts/user-location-map.js"));
}

<div id="sellgearContentWrapper">
    <h1>Sell Us Your Gear</h1>

   @Html.Raw(Model.RcContent.PageBody)
    
    @using (Html.BeginForm()) {
        <div id="sellgearwrapper" class="clearfix">
            <div class="formColumn">
                <h3>Your Info</h3>
                @Html.LabelFor(m => m.Name):
                @Html.TextBoxFor(m => m.Name)
        
                @Html.LabelFor(m => m.Email):
                @Html.TextBoxFor(m => m.Email)
        
                @Html.LabelFor(m => m.Phone):
                @Html.TextBoxFor(m => m.Phone)
        
                @Html.LabelFor(m => m.City):
                @Html.TextBoxFor(m => m.City)
        
                <div class="dualbox clearfix">
                    <div>
                        @Html.LabelFor(m => m.State):
                        @Html.TextBoxFor(m => m.State)
                    </div>
                    <div>
                        @Html.LabelFor(m => m.Zip):
                        @Html.TextBoxFor(m => m.Zip)
                    </div>
                </div>
            </div>
            <div class="borderColumn"></div>
            <div class="formColumn gearInfoColumn">
                <h3>Your Gear Info</h3>
        
                @Html.LabelFor(x => x.GearType):
                @Html.DropDownListFor(x => x.GearType, Model.GearTypeOptions)
        
                @Html.LabelFor(m => m.MakeAndModel):
                @Html.TextBoxFor(m => m.MakeAndModel)
        
                @Html.LabelFor(m => m.Color):
                @Html.TextBoxFor(m => m.Color)
        
                @Html.LabelFor(m => m.Year):
                @Html.TextBoxFor(m => m.Year)
        
                @Html.LabelFor(m => m.Condition):
                @Html.DropDownListFor(x => x.Condition, Model.ConditionOptions)
            </div>
    
            <div class="largeFormColumn">
                @Html.LabelFor(x => x.Describe):
                @Html.TextAreaFor(x => x.Describe, new {style="margin-top:10px;height:83px;"})
        
                @Html.LabelFor(x => x.Modifications):
                @Html.TextAreaFor(x => x.Modifications)
            </div>
        </div>

        <div class="form-field inputPot">
            <label>Please do not enter anything in the following field</label>
            @Html.HoneypotInput()
        </div>
    
        <div id="sellgearPhotoUpload" class="clearfix">
            <h3>
                Gear Photos
            </h3>
        
            <div id="photoGearWrapper" class="clearfix">
                <div class="imageUploader"> @Html.EditorFor(x => x.PictureOne.PictureId)</div>
                <div class="imageUploader"> @Html.EditorFor(x => x.PictureTwo.PictureId)</div>
                <div class="imageUploader"> @Html.EditorFor(x => x.PictureThree.PictureId)</div>
                <div class="imageUploader"> @Html.EditorFor(x => x.PictureFour.PictureId)</div>
            </div>
        </div>
    
        <div class="sellGearFormButton">
            <input type="submit" value="Submit" />
        </div>
    }
</div>

@section right
{
    @if (Model.IsFranchiseSite)
    {
         @Html.Action("LocationSidebar", "Franchisee")
    }
    else
    {
        @Html.Partial("_HowItWorksVideoSidebar")

          @Html.Partial("_UserLocation")
    }
}

Presentation/Nop.Web/Views/SellYourGear/Index.Mobile.cshtml
@model Nop.Web.Models.SellYourGear.CommonViewModel
@{
    Layout = "~/Views/Shared/_MobileLayout.cshtml";
    Html.AppendTitleParts(Model.RcContent.Meta.Title);
    Html.AppendMetaDescriptionParts(Model.RcContent.Meta.MetaDescription);
}

<section>
    <h1>@Model.RcContent.PageTitle</h1>

    <p>Music Go Round can help you trade your quality used musical instruments & equipment in for something new, used or for cash. To get started:</p>

    <ol>
        <li>Call your local @Html.ActionLink("Music Go Round location", "Index", "Home") to find out the most wanted and requested items in your city.</li>
        <li>Make sure your items are clean, in good condition and include all necessary parts.</li>
        <li>Bring them to your local store for trade or payment on the spot.</li>
    </ol>
</section>

Presentation/Nop.Web/Views/SellYourGear/Index.cshtml
@model Nop.Web.Models.SellYourGear.CommonViewModel

@{
    Layout = "~/Views/Shared/_Root.cshtml";
    Html.AppendScriptParts(@Url.Content("~/Scripts/user-location-map.js"));
    Html.AppendTitleParts(Model.RcContent.Meta.Title);
    Html.AppendMetaDescriptionParts(Model.RcContent.Meta.MetaDescription);
}

<h1 class="big-page-title">Sell Us Your Gear</h1>
<div class="how-it-works-page">
    <div class="centerwrapper">
        <div class="intro-text">
                Music Go Round<sup>&reg;</sup> is the place to go for used, musical instruments and music gear! <br/>For 30 years Music Go Round has specialized in buying, selling and trading used musical equipment all day, every day. You will find a huge variety of cool, used gear in our stores and online. To ensure that we are providing the best customer experience in our industry, our used gear is inspected, cleaned, and prepped so the used gear you’re buying is always in great working condition.
            
        </div>
    </div>
    @if (!Model.IsFranchiseSite)
    {
        <div class="golden-search-bar gold-blend">
            <div class="find-a-store-wrapper">
                <div mgr-location-search form-id="'findLocationHome'" label="'Find A Store'" place-holder-text="'Zip Code or City & State'" use-async="true" action-url="'/Locations/ListAsync'" layout="'one-line'"></div>
            </div>
        </div>
        @Html.Partial("~/Views/Locations/_LocationSearchResult.cshtml")
    }
    <div class="how-it-works-video" style="background-image: url('http://img.youtube.com/vi/NBI-MXCWprw/maxresdefault.jpg')">
        <a href="" class="play-video-button gold-blend">
            <div class="big-title">How It Works</div>
            <div class="play-text">Play Video</div>
        </a>
        <div class="overlay-video">
            <div id="youtubeEmbed"></div>
        </div>
    </div>
    <div class="how-it-works-page">
        @Html.Partial("~/Views/Home/_HowItWorksCallout.cshtml", "Selling Us Your Gear Is Simple")
    </div>
    <div class="faq-section">
        <div class="inner-wrapper centerwrapper">
            <div class="title">Frequently Asked Questions</div>
            <div class="faq-item">
                <div class="question">HOW CAN I GET THE MOST WHEN SELLING MY GEAR?</div>
                <div class="answer">
                    <p>Music Go Round<sup>&reg;</sup> buys all kinds of musical instruments and equipment daily.  We do offer the best possible price to every seller, based on the supply, demand and condition of your specific products.  However, making sure the product is clean, functional and has all of the related accessories, manuals and adapters will certainly improve the wholesale value of your gear.</p>
                </div>
            </div>
            <div class="faq-item">
                <div class="question">HOW WILL YOU VALUE MY EQUIPMENT?</div>
                <div class="answer">
                    <p>Our certified buyers receive extensive training on how to appropriately value all categories of musical instruments and equipment.  In a “typical” situation, we will pay 40-60% of what we have deemed to be the fair market value of your products.  Every product is unique and in some circumstances, the value will fluctuate based on supply, demand, condition, currency of the product in question and other market factors.</p>
                </div>
            </div>
            <div class="faq-item">
                <div class="question">HOW DOES MUSIC GO ROUND PAY?</div>
                <div class="answer">
                    <p>Music Go Round pays you on the spot, typically in the form of an official company check.  Please bring a valid driver’s license or government issued identification card as required by state laws.  You must be 18 years old and the legal owner of the product to sell to Music Go Round.  Proof of ownership may be requested during the buy transaction.</p>
                </div>
            </div>
            <div class="faq-item">
                <div class="question">I LOVE MUSIC GO ROUND AND WANT TO WORK FOR THEM.  ARE YOU HIRING?</div>
                <div class="answer">
                    <p>All of our hiring happens in our stores.   Please visit the store website or contact the store management to inquire about available positions and to supply a resume.</p>
                </div>
            </div>
        </div>
    </div>
</div>


@section FooterScripts{
    @if (!Model.IsFranchiseSite)
    {
        <script type="text/javascript" src="/Scripts/libs/markerwithlabel.js"></script>
    }
    <script type="text/javascript">
        $(function() {
            var tag = document.createElement('script');
            tag.src = 'https://www.youtube.com/iframe_api';

            var firstScriptTag = document.getElementsByTagName('script')[0];
            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

            var player;
            var playerLoaded = false;

            function onYtReady(e) {
                playerLoaded = true;
                e.target.playVideo();
            };

            function initYtPlayer() {
                player = new YT.Player('youtubeEmbed', {
                    height: '405',
                    width: '720',
                    videoId: 'NBI-MXCWprw',
                    events: {
                        'onReady': onYtReady
                    },
                    playerVars: {
                        'rel': 0,
                        'showinfo': 0
                    }
                });
            }

            $('.overlay-video').on('click', function(e) {
                $(this).hide();
                player.pauseVideo();
                $('body').css('overflow', '');
            }).children().on('click', function(e) {
                e.stopPropagation();
            });
            $('.play-video-button').on('click', function(e) {
                e.preventDefault();
                $('.overlay-video').show();
                if (!playerLoaded) {
                    initYtPlayer();
                }
                $('body').css('overflow', 'hidden');
            });
        });
    </script>
}

Presentation/Nop.Web/Views/SellYourGear/Submitted.cshtml
@model Nop.Web.Models.SellYourGear.CommonViewModel

@{
    Html.AppendTitleParts(Model.RcContent.Meta.Title);
    Html.AppendMetaDescriptionParts(Model.RcContent.Meta.MetaDescription);
    Layout = "~/Views/Shared/_ColumnsTwoRightColumn.cshtml";
    Html.AppendScriptParts(@Url.Content("~/Scripts/user-location-map.js"));
}

<div id="sellgearContentWrapper">
   <h2>Your Sell Us Your Gear request has been submitted.</h2>
</div>

@section right
{
    @if (Model.IsFranchiseSite)
    {
         @Html.Action("LocationSidebar", "Franchisee")
    }
    else
    {
        @Html.Partial("_HowItWorksVideoSidebar")

          @Html.Partial("_UserLocation")
    }
}

Presentation/Nop.Web/Views/SellYourGear/_OutOfRange.cshtml
<p>We’re sorry, you are currently out of range and are unable to submit gear to one of our stores.</p>
<p>Need a shop near you? Consider opening a Music Go Round Store yourself.</p>
<p>Our franchisees are our customers - business-oriented people with a love for music! This gives them a winning edge at understanding the needs of their market. 
    They buy the best used gear in good condition and offer fair trade-ins and payment on the spot, building customer loyalty with every transaction.</p>
<p>Get started today! <a class="learn-more" href="@Url.Action("Index", "Own")">Click Here To Learn More</a></p>

Presentation/Nop.Web/Views/SellYourGear/_SelectLocation.cshtml
@using Nop.Web.Extensions
@model IEnumerable<Treefort.Portal.Queries.Geo.LocationModel>
    
<h3>Choose a location to submit your gear:</h3>
<table class="locations">
@foreach(var location in Model) {
    <tr class="location" data-href="@Url.Action("Form", "SellYourGear", new {locationId = location.Id, zip = ViewBag.Zip})">
        <td class="arrow"><span>&raquo;</span></td>
        <td>
            <h3>@location.City</h3>
            <span>@location.PhoneNumber</span> <br />
        </td>
        <td>
            <h3 class="distance-mileage">@(location.Distance.HasValue ? Math.Round(location.Distance.Value,1) + " mi" : "NA")</h3>
            <a href="@Url.GoogleDirections(location)" target="_blank">Map</a>
        </td>
    </tr>
    <tr class="spacer"><td colspan="3"></td></tr>
}
</table>